### ISSUE TITLE
Radial gradients

### ISSUE THREAD

**Issue by raphlinus** [linebender/vello#153]
Right now there's (somewhat rough) linear gradient support, but radial gradients are part of both the piet imaging model and [COLRv1](https://github.com/googlefonts/colr-gradients-spec). Actually COLRv1 has a "sweep" gradient as well, which is not part of piet.

To avoid encoding bloat, this should happen after variable size scene encoding (#152).

There are a bunch of edge cases, sadly, and we'll need to figure out how to handle them. It wouldn't be a bad idea to have or refer to a spec that nails down behavior.

Below are some notes.

WebRender used to have a shader for radial gradients, but [got rid of it](https://bugzilla.mozilla.org/show_bug.cgi?id=1687977) not long ago in favor of a cached texture. I can see the value in that for web content, but when the gradient itself might be dynamic, it may be better to do it in the shader. In any case, we currently don't have an infrastructure for cached resources (it is coming, though).

Another [WebRender change](https://hg.mozilla.org/integration/autoland/rev/85e23b4d97ac) changed the way radial gradients were rendered. It's not obvious to me whether the "before" or "after" state is a better model for us; in any case, linking the patch here lets us look at both.

Apple has a good page with info about [radial gradients in Quartz](https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/dq_shadings/dq_shadings.html). It's not normative, but might be interesting.

And here's the relevant section from the [SVG spec](https://www.w3.org/TR/SVG2/pservers.html#RadialGradientNotes). It probably should be considered normative. I'm not sure if the expectation is that it's exactly the same as COLRv1, but I would be surprised if there were major differences.

Probably adding more references to "sweep" gradients should be followup, can be posted to this issue.

**Comment by nicoburns** [comment]
Can this be closed? I believe Vello now supports Radial and Sweep gradients?

**Comment by raphlinus** [comment]
Yes, should have been closed a while ago, thanks for noticing.
