### ISSUE TITLE
wgpu Adapter and Surface might not be compatible

### ISSUE THREAD

**Issue by rosefromthedead** [linebender/vello#224]
Since `RequestAdapterOptions` field `compatible_surface` is not specified ([see here](https://github.com/linebender/piet-gpu/blob/a7dbeb3b9be0573c4aae2b2703a33d391178ae44/piet-wgsl/src/util.rs#L34)), wgpu may not give an adapter that can render to the display. But the current API means the Instance and Adapter are constructed at the same time and the Surface is constructed later, so without changing the API (which admittedly seems pretty natural how it is), it's not possible to fix this. Maybe it's worth separating Instance and Adapter creation? Or making the user provide Instance and Surface themselves?

FWIW I ran into this incompatibility on my intel+nvidia laptop, but the default `PowerPreference` should select intel, so I might just not have *any* compatible combinations. Still might be worth allowing this for other machines.

**Comment by dfrg** [comment]
Thanks for reporting this. The intent behind separating surface and device creation is to support multiple windows (which may come and go, particularly in UI contexts) that can share resources on a single device. If the current design is failing on dual GPU setups, it’s definitely something that we need to address even if that makes the API less pleasant. 

I am curious about the error message. Is it general surface incompatibility or is the format (we unconditionally choose Bgra8Unorm) incompatible?

**Comment by rosefromthedead** [comment]
The error message is `Error in Surface::configure: surface does not support the adapter's queue family`, so it seems not to be pixel format, but idk how to check.

**Comment by rosefromthedead** [comment]
IMO it would be good to have error handling at surface creation time, to request an adapter that is compatible with the new surface if the current adapter is not, and then continue using both adapters for their respective surfaces. This means that if I have 2 cards with 1 display each then my app can draw to surfaces on both displays simultaneously without incompatibility issues, which might not be possible if vello only keeps one adapter around. Helpfully, it also solves the original problem :P 

Here's hoping it's not too hard to add multi-adapter support?

**Comment by dhardy** [comment]
Just a little note, I had a [similar report recently](https://github.com/kas-gui/kas/issues/367#issuecomment-1357956379), and while at first glance use of a `compatible_surface` to ensure compatibility may appear a good idea, my conclusion was that this only really does anything for users with multiple GPUs (in the reporter's case, Intel iGPU + NVidia discrete graphics). The better solution, for a general purpose GUI, is to make the surface compatible with as many adapters as possible (including old Intel iGPUs).

**Comment by rosefromthedead** [comment]
Looks like you did that by using the fifo present mode, but vello was already using that before my change, and still didn't work.
