### ISSUE TITLE
Dragging vello windows is laggy

### ISSUE THREAD

**Issue by nicoburns** [linebender/vello#230]
When attempting to drag a window which is rendering using vello by grabbing it's titlebar with the mouse there is a noticeable lag (I would guess at least 500ms) before the window starts to move. This does not happen with any other apps on my system, so I *think* vello is the common factor here.

Tested on:
- macOS 13.0.1 (M1)

This applies to all uses of Vello I have found including:
- The examples in this repo
- The [Xilem](https://github.com/linebender/xilem) demo
- Examples in the [Blitz](https://github.com/DioxusLabs/blitz) repo

**Comment by DJMcNab** [comment]
Does this still occur when you run these tests in release mode?

**Comment by nicoburns** [comment]
> Does this still occur when you run these tests in release mode?

Yes, this occurs in both debug and release modes.

It seems to be in issue with initiating the drag, once the initial lag has occurred it is possible to move the windows around without lag so long as I keep the mouse button pressed. But once I release the drag, initiating a new one lags again.

**Comment by nicoburns** [comment]
Hmm... this seems to be the same as https://github.com/rust-windowing/winit/issues/1737 (including that it's an interaction with the Magnet utility app)

**Comment by DJMcNab** [comment]
It's not reasonable for us to fix and debug the behaviour of applications which intentionally break operating system functions.

I'll suggest the recommendation which follows from the linked issue, which is if you wish the window dragging to not be laggy, disable the offending application.
