### ISSUE TITLE
Validation error on MacOS, path_coarse_full

### ISSUE THREAD

**Issue by simbleau** [linebender/vello#274]
I think there's an issue here, just not really smart enough to track it down.

https://github.com/linebender/vello/blob/020a7f5c016ab5c572cefbe169f19082a0e34ffe/shader/path_coarse_full.wgsl#L238

```
2023-02-05T23:31:49.074966Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2023-02-05T23:31:49.196691Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_compute_pipeline
      note: label = `path_coarse_full`
    Internal error: Metal: program_source:243:14: warning: unused variable '_e43'
        uint _e43 = metal::atomic_fetch_or_explicit(&bump.failed, STAGE_PATH_COARSE, metal::memory_order_relaxed);
             ^
program_source:485:29: warning: unused variable '_e390'
                        int _e390 = uint(tile_ix) < 1 + (_buffer_sizes.size6 - 0 - 8) / 8 ? metal::atomic_fetch_add_explicit(&tiles[tile_ix].backdrop, backdrop, metal::memory_order_relaxed) : DefaultConstructible();
                            ^
program_source:538:70: error: cannot take the address of an rvalue of type 'metal::uint' (aka 'unsigned int')
                        uint _e461 = metal::atomic_exchange_explicit(&uint(tile_ix_1) < 1 + (_buffer_sizes.size6 - 0 - 8) / 8 ? tiles[tile_ix_1].segments : DefaultConstructible(), _e458, metal::memory_order_relaxed);
```

**Comment by raphlinus** [comment]
Is this on most recent versions of everything? This looks a lot like https://github.com/gfx-rs/wgpu/issues/3136 which was fixed by https://github.com/gfx-rs/naga/pull/2099.

**Comment by simbleau** [comment]
So I made sure I was on wgpu 15 and using the most recent version.

I no longer get that problem. I get new problems ;)

I cannot seem to make the run_wasm work. On your end, I see a problem with adapter.features() from webgpu causing a crash.

<img width="1567" alt="image" src="https://user-images.githubusercontent.com/48108917/217133174-fb8792aa-414f-4e75-bf96-77d2d365e3cc.png">


On my end, I get a bug saying there's no way to allocate a storage buffer.

<img width="551" alt="image" src="https://user-images.githubusercontent.com/48108917/217133107-56447471-15fa-42b9-8b5f-7fdebf7c970b.png">
