### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by DJMcNab** [linebender/vello#285]
At the moment, our error types are just `Box<dyn Error>`:
https://github.com/linebender/vello/blob/61ae3cde03a4cc88d6b312fd6e18384d1fd5dfa3/src/engine.rs#L29

I'm actually having trouble finding places where this is constructed, as e.g.:
https://github.com/linebender/vello/blob/61ae3cde03a4cc88d6b312fd6e18384d1fd5dfa3/src/engine.rs#L160-L166
Also returns an `Error`, despite being infallible (any error which occurs is handled by wgpu's [error handler](https://docs.rs/wgpu/latest/wgpu/struct.Device.html#method.push_error_scope) instead)

The only case I can see is in:
https://github.com/linebender/vello/blob/61ae3cde03a4cc88d6b312fd6e18384d1fd5dfa3/src/lib.rs#L156

I'm sure there are probably other reasons it's so widely used, though

I think the standard is to use [`derive(Error) from thiserror`](https://docs.rs/thiserror/latest/thiserror/) for making error enums. 

In #284, @dfrg correctly observed pointed out that finishing clips is a another point where errors can occur. This is an interesting case, because there are a number of philosophies around handling it. Skia ignores similar cases, and returning an error would be rather unergonomic for the majority of cases where this wouldn't be hit.

I see some possible solutions:
- Return an error, and let callers deal with it
- Return an error, but add a helper which just drops the error
- Return an error, but add a helper which panics on error
- Poison the `SceneBuilder`, meaning that unless the a special method (e.g. `take_errors()->Option<...>`) is called, the `SceneBuilder` panics when dropped

**Comment by simbleau** [comment]
I think `thiserror` is the winner in terms of public adoption for libraries (anyhow for binaries). Sounds like a good idea. Any place `Box<dyn Error>` exists should probably be replaced.

As for your solutions, I think another decent approach would be to have two versions of the API calls in question, like `try_x() -> Result<_, Error>` and `x() -> _`.
