### ISSUE TITLE
Text clipping artifacts

### ISSUE THREAD

**Issue by Stumblinbear** [linebender/vello#286]
It seems as though text overflowing a clipping layer doesn't work properly. I've added the following to the `animated_text` test scene, around the second "Animated text!" element

```rust
const X0: f64 = 50.0;
const Y0: f64 = 450.0;
const X1: f64 = 200.0;
const Y1: f64 = 950.0;

let path = [
    PathEl::MoveTo((X0, Y0).into()),
    PathEl::LineTo((X1, Y0).into()),
    PathEl::LineTo((X1, Y0 + t * (Y1 - Y0)).into()),
    PathEl::LineTo((X1 + t * (X0 - X1), Y1).into()),
    PathEl::LineTo((X0, Y1).into()),
    PathEl::ClosePath,
];

sb.push_layer(Mix::Clip, 1.0, Affine::IDENTITY, &path);
{
    params.text.add(
        sb,
        None,
        text_size,
        None,
        Affine::translate((110.0, 700.0)),
        s,
    );
}
sb.pop_layer();
```

Which results in many vertical bars clipping the text, instead of the remaining text being clipped in its entirety:

![image](https://user-images.githubusercontent.com/11092351/221719139-2000a678-78de-4e09-a594-8eb33d5fa41f.png)

**Comment by DJMcNab** [comment]
I did a little bit of investigation. This (naturally) doesn't apply to only text, I made a path with 2 linetos which worked (although I couldn't reproduce with a rectangle). This also doesn't need the sub-fragment, just the path on its own worked.

And unsurprisingly, the new clipping boundary is a (16px by 16px) tile edge. It seems that the parts of the path in the left-most tile column affected by the path are still displayed. This seems likely to be an off-by-one error, I'm just not sure where.

**Comment by dfrg** [comment]
Nice! This was appearing in some Lottie animations but the scene complexity there made it difficult to track anything down. Narrowing this to a much smaller test case is exceptionally helpful.

**Comment by armansito** [comment]
#335 fixes this bug. I added @Stumblinbear's repro code to a new test scene that demonstrates the problem and the fix.

**Comment by armansito** [comment]
Please re-open if you still see this issue on main.
