### ISSUE TITLE
Is it possible to use vello in my existing C/C++ program?

### ISSUE THREAD

**Issue by ChengduLittleA** [linebender/vello#299]
Hi there! I was wondering is it possible to use vello to draw complex vector graphs dynamically in my existing C/C++ program? My program uses GLX on linux. Is it possible at all? Or will there be a port of some kind? Thanks!

**Comment by raphlinus** [comment]
There are no plans for official C++ bindings. That said, there are some crates for C++ interop (bindgen, cxx, crubit, and others), so it would be possible with some patience to make it work. In general, I think it will be much better experience to write the application in Rust.
