### ISSUE TITLE
Better composition of `SceneFragment` and `Scene`

### ISSUE THREAD

**Issue by Pieresqi** [linebender/vello#342]
Hello there,  I would like to do better composition of fragments and scenes but it's very limiting to do so (Or I missed some public API).

So I would like to propose few things:
1. `SceneFragment` and `Scene` should derive `Clone`.
2. Make their `Encoding` public.
3. Alllow me to modify `SceneFragment` without clearing it.

**Comment by Stumblinbear** [comment]
Seconding this. I'm looking for a good way to clone a fragment so I can work on the next frame while still allowing the previous fragment to be used for rendering

**Comment by PoignardAzur** [comment]
I'm looking into Vello's API, especially the Scene-based types. This is interesting!

> Make their Encoding public.

Why this in particular? The other seem obvious, but having the encoding be private seem like a natural encapsulation boundary.

**Comment by Pieresqi** [comment]
> Why this in particular?
I am not sure anymore. I forgot ...
