### ISSUE TITLE
Miscompilation of `fill_paths` by `naga`

### ISSUE THREAD

**Issue by Jasper-Bekkers** [linebender/vello#361]
Friendly heads up. I've already filed an issue on the naga repo https://github.com/gfx-rs/naga/issues/2471

**Comment by raphlinus** [comment]
Thanks! I haven't been actively tracking the HLSL-out of the Vello shaders, last time I checked they were quite broken. I do expect there to be a tail of problems, both at the naga level and in vendor GPU compilers, so it's useful to shake those out.

**Comment by Jasper-Bekkers** [comment]
After manually patching this and making other adjustments to accomodate our specific codebase everything worked, fwiw. So it looks like hlsl-out has matured a bit since then.

**Comment by raphlinus** [comment]
Closing as #382 works around it. We might come back to it when naga fixes the underlying problem, but it's a low priority. Thanks for the heads-up!
