### ISSUE TITLE
Poland example SVG does not render correctly

### ISSUE THREAD

**Issue by sirxyzzy** [linebender/vello#373]
On the edge of the wings there are flecks of black, where they should render white, see the good and bad images, the "good" was using Edge to render, the bad was a screen shot from loading the example flag of poland when running the examples (cargo run --p with_winit)

(ignore scaling differences in the images)

<img width="329" alt="good" src="https://github.com/linebender/vello/assets/7274181/03d10303-017c-49eb-b5a8-41ccaba5a431">
<img width="285" alt="bad" src="https://github.com/linebender/vello/assets/7274181/4bae08ec-91bd-4652-9533-010343b655cc">

**Comment by raphlinus** [comment]
I believe this may be a very simple problem, the black splotches correspond to transparent regions in the SVG. There is a rectangle, but it's set as `display="none"` and that appears to respected by usvg (I haven't dug into it).

A workaround is to add `--base-color white` to the command line.

**Comment by DJMcNab** [comment]
The SVG download feature is no longer present, and neither is the SVG parser used with this image. I'm going to close this one out
