### ISSUE TITLE
[CPU shaders] Assertion failure in path_tiling stage when rendering Coat of Arms of Poland.svg

### ISSUE THREAD

**Issue by armansito** [linebender/vello#378]
To reproduce run the following:
```
 cargo run -p with_winit -- ./examples/assets/downloads/Coat\ of\ Arms\ of\ Poland.svg --use-cpu
```
Which fails with: `thread 'main' panicked at 'assertion failed: xy0.x >= tile_xy.x && xy0.x <= tile_xy1.x', src/cpu_shader/path_tiling.rs:129:9`

With some more debug information:
```
thread 'main' panicked at 'p0: Vec2 {
    x: -0.18100956,
    y: 8.772132e-14,
}, p1: Vec2 {
    x: 677.49286,
    y: 8.772132e-14,
}, xy0: Vec2 {
    x: -0.18100956,
    y: 8.772132e-14,
}, xy1: Vec2 {
    x: 16.0,
    y: 0.0,
}, tile_xy: Vec2 {
    x: 0.0,
    y: -16.0,
}, tile_xy1: Vec2 {
    x: 16.0,
    y: 0.0,
}', src/cpu_shader/path_tiling.rs:129:9
```
I'm triggering the assertion consistently with these values.

**Comment by raphlinus** [comment]
Minimal repro case, based on extracting the offending line segment from the assert failure:

```svg
<svg width="1200" height="1200" viewBox="0 0 1200 1200" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M-0.36201912 1.7544264e-13L1354.9857 1.7544264e-13 100 100" fill="#ff0"/>
</svg>
```

**Comment by raphlinus** [comment]
Ok, I've slept on it, and I believe the following will work. Compute b by taking the min with 0.99999994, which will guarantee it's strictly less than 1. Then compute floor(a * (n - 1) + b) and check whether it's equal to max(1, ceil(max(x0, x1)) - floor(min(x0, x1))) - 1. Note: that's the same value as for computing the count, and it's equal to the width in grid cells of the rasterized line minus one. If not equal, bump a by some epsilon (I believe 1e-9 is fine) with the sign needed to make that equal.

There's more work that can be done to validate this, but I *believe* that would result in fully robust rendering, and also reduces the pressure on the division operation to compute a. Note that this would also apply to multisampled rendering in fine (see the reviews for the msaa PR, linked above).

**Comment by raphlinus** [comment]
1e-9 is not fine, we're in f32 world, that's less than 1 ulp. I think 1e-7 is adequate, but the argument is subtle.

**Comment by raphlinus** [comment]
I believe this can be considered fixed as per the linked PR.
