### ISSUE TITLE
paper-2 doesn't render correctly

### ISSUE THREAD

**Issue by armansito** [linebender/vello#381]
paper-2 SVG from the [MPVG](https://w3.impa.br/~diego/projects/GanEtAl14/) input set renders incorrectly. Most of the content is missing. This bug seems to predate the MSAA and the CPU shader work and is reproducible with the previous architecture:

<img width="880" alt="Screenshot 2023-10-11 at 10 31 12 PM" src="https://github.com/linebender/vello/assets/6933700/d5a3cab4-361f-4d27-80d1-6294857be040">

**Comment by raphlinus** [comment]
This is straightforward, it just needs `--base-color white`
