### ISSUE TITLE
doc/vision.md

### ISSUE THREAD

**Issue by ratmice** [linebender/vello#450]
Being somewhat late to vello, having not played with it during the piet-gpu stages of development.
It reads to me like doc/vision.md is somewhat out of date with the current state of things,
In particular the section [Why not wgpu](https://github.com/linebender/vello/blob/main/doc/vision.md#why-not-wgpu) doesn't seem relevant anymore since vello *does* use wgpu.

So that could perhaps use a pass over it to better reflect the current state of things.

**Comment by PoignardAzur** [comment]
See https://github.com/linebender/vello/issues/488
