### ISSUE TITLE
Tracking issue for supporting clip-path in vello-svg?

### ISSUE THREAD

**Issue by Enter-tainer** [linebender/vello#466]
Hi! I'm the author of [typst-preview](https://github.com/Enter-tainer/typst-preview). Recently I'm investigating GPU accelerated 2d vector rendering library and find it surprisingly hard. And vello seems to be the only suitable rust library i've found!

For some background, typst is a new typesetting system (written in rust) which aims to be as powerful as LaTeX but still being lightning fast. And [typst-preview](https://github.com/Enter-tainer/typst-preview) is a 3rd party util that compiles and render your typst source code on every keystroke. So the e2e latency is important. Typst can produce pdf/svg/png as output. When exporting to svg, typst compiles every glyph into paths and embed images into svg file using data url. Currently we use the browser to display svg, and we use a VDOM based incremental svg renderer: when updating, we only replace the changed part of the svg DOM tree. However, it still feels laggy when there is a lot of paths in document. Users with lower-end devices also complain that the browser uses too much resource.

I believe a gpu based, native application would have better performance than browser. And I'm trying to render svg produced by typst using vello_svg. Vello renders them pretty well. And the rendering speed is insane!
<img width="784" alt="image" src="https://github.com/linebender/vello/assets/25521218/c1ad1b88-38e0-4747-b9cd-48bd3da7c1b8">

I just read the code of `vello_svg` and find it simply renders all paths in svg tree and ignore other things like image or clip-path. There is already a tracking issue for images in #176. I want to know is it hard to implement clip-path? I can offer help if it is not too hard.

**Comment by dfrg** [comment]
The composition mode should be `SrcOver`, or just pass `Mix::Clip` as the blend mode and it should handle that properly. Otherwise, I think your code looks about right. The base path code calls `abs_transform()` on the path before use… I’m not sure if you need to do the same thing for `clip_path`.

**Comment by DJMcNab** [comment]
For those finding this later, `vello_svg` has been moved to https://github.com/linebender/vello_svg
