### ISSUE TITLE
`Scene::reset()` should be renamed to `Scene::clear()`

### ISSUE THREAD

**Issue by PoignardAzur** [linebender/vello#469]
Should be self-explanatory.

If we visualize Scene as a container for encoded draw commands, `clear()` is the obvious name.

**Comment by xStrom** [comment]
We decided at office hours 2024-02-29 that we will not go ahead with this rename. The `reset` name was carefully chosen to not collide with the already existing `clear` method in Piet's API.

**Comment by PoignardAzur** [comment]
That's fine, I added a doc alias instead.
