### ISSUE TITLE
Long startup time under DX12

### ISSUE THREAD

**Issue by AlexanderHarrison** [linebender/vello#498]
On my (not ancient, not modern) machine, shader compilation under DX12 takes on the order of seconds and is by far the bottleneck of startup time for simple applications. This is with threaded compilation and Dxc.

Is there a way vello could pass through precompiled DX12 shaders or somehow optimize the shaders for compilation? Or is this something that would require work on wgpu?

I would like to use the Vulkan backend on windows but I've found it a little buggy and much more prone to crashing than using Vulkan on linux.

**Comment by AlexanderHarrison** [comment]
[Just saw the blog post](https://linebender.org/blog/tmix-02/). Sounds like you all are way ahead of me. :)

**Comment by DJMcNab** [comment]
I'm not planning on implementing pipeline caching for DirectX12. I think gfx-rs/wgpu#5293 is the place to track this[^vulkan], although it's realistically at least blocked on gfx-rs/wgpu#5319 (which is waiting on review bandwidth from the wgpu team)

[^vulkan]: I made that issue to only track the Vulkan version, but it's been renamed away from that
