### ISSUE TITLE
[Question] was rust-gpu evaluated?

### ISSUE THREAD

**Issue by nerdachse** [linebender/vello#501]
Hello!

Out of pure curiosity, was `rust-gpu` (https://github.com/EmbarkStudios/rust-gpu) instead of `wgsl` evaluated at some point?

I know it says in their README that the first focus is graphics shaders and compute being a second, hence I ask if you considered it and hit any sharp edges.

Again, pure curiosity!

**Comment by raphlinus** [comment]
Absolutely. I'd love to have something along the lines of rust-gpu, but it is sadly not mature enough. Another major concern was portability - WGSL is carefully designed to work well even on Vulkan 1.0, while rust-gpu requires more modern GPUs. This is a tradeoff of course, there are also advantages to being able to depend on modern features.

For evaluating shader languages, I strongly recommend implementing prefix sum. That should only be about a hundred lines of code (give or take) but shakes out a lot of the potential problems and also is a good chance to show off the abstraction capabilities of the language. In particular, I'd love to have a Rust trait to express a monoid, and a scan implementation generic on the monoid. For extra points, have that trait include methods for subgroup reduction and scan with a default implementation based on subgroup shuffle.

The currently most promising alternative to WGSL is [slang](https://github.com/shader-slang/slang). I've lightly prototyped prefix sum, but run into issues with default trait methods (called "extension" in slang). I should file issues there :)

BTW, there's nothing wrong with using issues to ask questions, but [Zulip](https://xi.zulipchat.com/) might be better for such discussions, in this case the `#gpu` stream.

**Comment by nerdachse** [comment]
I am sorry for opening an issue, it seemed inappropriate to me too, but there was no discussions tab and I am not on zulip (too many different messengers these days, but worry not, once xilem is ready I'll write the chosen one to rule them all! ;))

Thanks a bunch for taking time to answer and in such depth! Feel free to close and again: sorry for opening an issue when it's clearly not!
