### ISSUE TITLE
Appending an `Encoding` to a `Scene`

### ISSUE THREAD

**Issue by waywardmonkeys** [linebender/vello#530]
I don't see a way to append an `Encoding` to a `Scene` at the moment.

I could see doing this as:

* New method on `Scene`: `Scene::append_encoding()`
* New method on `Scene`: `Scene::get_encoding_mut()` and then work with that underlying encoding
* Allow wrapping an existing `Encoding` as a `Scene` and then use the existing `Scene::append()`

**Comment by waywardmonkeys** [comment]
This might need feedback from @raphlinus or @armansito

**Comment by waywardmonkeys** [comment]
Some further thoughts:

Doing a `Scene::append_encoding()` or allowing `Scene::from_encoding()` and then using `Scene::append()` would both require that the `BumpEstimator` on the `Scene` be updated to include what was in the `Encoding`.

Doing a `Scene::append_encoding()` would require that either the `Encoding` have its own `BumpEstimator` or that it be repeatedly calculated on every `Scene::append_encoding()` call.

Doing a `Scene::from_encoding()` would allow for it to cache that encoding's estimator.

Doing the middle option of a `Scene::get_encoding_mut()` would complicate bump estimator code given the current design.

**Comment by waywardmonkeys** [comment]
This is all related to https://xi.zulipchat.com/#narrow/stream/147932-chatter/topic/SVG.20icon.20libraries

**Comment by armansito** [comment]
I think all of the approaches you described are reasonable. My main concern wrt adding a `Scene::get_encoding_mut` is that it may become a maintenance issue if we decide to add additional state to Scene that makes it more than a simple wrapper around Encoding.

The BumpEstimator is one such example as you pointed out. I'm not too worried about that particular case though, as I'm planning to move the estimation from scene construction time to resolve time (which happens later in the pipeline, right before instantiating the resources for a render).

**Comment by waywardmonkeys** [comment]
I have submitted a PR that allows for `Scene::from(encoding)` or `encoding.into()` returning a `Scene`.  This would then work with passing the scene wrapping the encoding to `Scene::append()` without adding extra methods to `Scene` for `append_encoding` or the like and it is more typical Rust to do this than `Scene::from_encoding()`.
