### ISSUE TITLE
Minor issue: example 'simple' - when compiled standalone -  the render context needs to be unwrapped  

### ISSUE THREAD

**Issue by xabra** [linebender/vello#554]
` let mut render_cx = RenderContext::new().expect("Couldnt get render context");`
fixes the problem.  Not sure why it compiled OK when built inside the vello crate.

**Comment by waywardmonkeys** [comment]
This is due to an API change between `main` and the release. You should use the version from the tagged release.

**Comment by waywardmonkeys** [comment]
https://github.com/linebender/vello/tree/v0.1.0/examples/simple
