### ISSUE TITLE
How to figure out the correspondence of window size and image size

### ISSUE THREAD

**Issue by Boltzmachine** [linebender/vello#572]
I am trying to draw an image in vello. I found the size of the winit window mismatches the size of the image. So I wonder how I can find the relationship between two sizes to align them :)

**Comment by DasLixou** [comment]
Could you provide more information about what is misaligned? Maybe a picture?
When you mean that the aspect ratio is not correct, maybe you want to create a winit window with [`with_inner_size`](https://docs.rs/winit/latest/winit/window/struct.WindowAttributes.html#method.with_inner_size) or do other stuff like drawing outside so it fills the whole content or strech it (like what css `object-fit` property).
Or is it just to small? Maybe you need to convert between `LogicalSize` and `PhysicalSize`?

**Comment by Boltzmachine** [comment]
Thanks for your patience! Actually after some investigation, I found it is actually because:

I resize the image correctly to fit the window initially, and then my tiling window manager automatically resizes the window. making the image not fit the window anymore.

```rust

WindowEvent::Resume => {
    let mut image = read_image();
    resize_image_to_window(image, window);
}

WindowEvent::Resize (size) => {
    render_cx.resize_surface(...);
}
```
The result is
![image](https://github.com/linebender/vello/assets/56542320/310b53f3-8c08-43de-868d-aaf2aeff1e48)

If I delete the contents in `WindowEvent::Resize`, the image can still fit the window.
![image](https://github.com/linebender/vello/assets/56542320/7eaf6fbe-7a6e-4921-bc8d-d2cc6e5ed201)


Since `winit` does not provide a way to know if the window should be floating in advance, I am afraid there is no way to keep the image size after automatically resizing.

Feel free to close the comment if you think that is the case.

**Comment by DasLixou** [comment]
I wouldn't remove the code in the resize event, it maintains a smaller surface texture that just gets streched so it's smaller quality. 
What you could do is reset the scene (or a scene fragment) and re-encode the rectangle with the new inner size of the window, either on RedrawRequest, or, if you want to keep the scene for some reason, in the Resize event.

**Comment by Boltzmachine** [comment]
I see. Thanks for your suggestion!
