### ISSUE TITLE
Update ARCHITECTURE.md

### ISSUE THREAD

**Issue by DasLixou** [linebender/vello#577]
`ARCHITECTURE.md` is not up to date anymore because of #563 (and maybe other things? just had that in mind when mindlessly browsing through the repo)
`/src/` doesn't have `cpu_shaders/` and `shaders/` anymore.

**Comment by waywardmonkeys** [comment]
That change actually happened in #563 ... my #570 was just fixing an issue that resulted from #563.

**Comment by DasLixou** [comment]
Oh, you're right 😅 how did I oversee that?
