### ISSUE TITLE
Add basic tests

### ISSUE THREAD

**Issue by PoignardAzur** [linebender/vello#611]
Vello has test scenes, but no integration tests.

Adding tests would help Vello contributors check that their modifications don't add regressions to the crate, and help us catch hidden bugs.

As a first step, we'd want to at least add some extremely basic tests, such as checking that Vello doesn't crash when we run a sample image through the CPU shaders.

**Comment by DJMcNab** [comment]
I'm not sure how this issue can now be actioned? I would have expected the integration tests in #439 to cover this use case.

See also #608

**Comment by PoignardAzur** [comment]
Well, then just remove these tests and do another PR that adds some tests!

**Comment by PoignardAzur** [comment]
But yeah, I feel a bit silly, especially since we talked about that PR an hour ago.
