### ISSUE TITLE
Rendering issue when clipping and stroking the same path

### ISSUE THREAD

**Issue by timtom-dev** [linebender/vello#616]
I'm trying to render a simple UI, and I'm using the same path to clip the contents of each button as well as stroke the border, but I'm getting some artifacts in the corners of some of the buttons. Is this a known issue?

![image](https://github.com/linebender/vello/assets/16622597/23e50bc3-6bef-4eea-b24e-1f5bef876fab)

**Comment by raphlinus** [comment]
Hm, that definitely looks like a rendering issue. Is there any chance you could make a minimal repro?

**Comment by timtom-dev** [comment]
Sure thing! I wasn't able to quickly repro the big black rectangle, but hopefully that's the same problem.

It only looks like it happens at certain coordinates, which is why the rectangle is at (60., 10.) it doesn't happen at 61, for example.

Swap this function in to the "simple" example in the vello repo:

```rust
fn add_shapes_to_scene(scene: &mut Scene) {
    let rect = RoundedRect::new(60.0, 10.0, 160.0, 100.0, 10.0);
    let stroke = Stroke::new(2.0);
    let fill = vello::peniko::Fill::NonZero;
    let mask_blend = vello::peniko::BlendMode::new(vello::peniko::Mix::Normal, vello::peniko::Compose::SrcOver);
    scene.push_layer(mask_blend, 1.0, Affine::IDENTITY, &rect);
    scene.stroke(&stroke, Affine::IDENTITY, Color::BLACK, None, &rect);
    scene.pop_layer();
}
```

![image](https://github.com/linebender/vello/assets/16622597/84dac27e-3a3c-483a-a0f1-f00a7dc2c32b)

**Comment by timtom-dev** [comment]
Oh I just remembered I also set the clear color to gray 😅

**Comment by timtom-dev** [comment]
So it turns out that this has nothing to do with clipping layers. The following code also exhibits the issue:

```rust
    let rect = RoundedRect::new(60.0, 10.0, 160.0, 100.0, 10.0);
    let stroke = Stroke::new(2.0);
    scene.stroke(&stroke, Affine::IDENTITY, Color::WHITE, None, &rect);
```

**Comment by DJMcNab** [comment]
I can reproduce.

Some triage:
1) This doesn't reproduce if we use the CPU "flatten" stage
2) There seem to be two issues:
    - The little poke, which only reproduces with the MSAA8 or MSAA16 rendering modes
    - The filling of the square, which is reproducible with any `AAConfig`
3) This only seems to reproduce near the top of the window for me
4) It doesn't seem to reproduce if the rectangle is at all rotated
5) It always seems to be at the join of the arc and the rectangle. This is the first/last point of the `RoundedRectangle`

The issue reproducing with area anti-aliasing, with no
![image](https://github.com/linebender/vello/assets/36049421/de310863-8481-45c2-a43a-7e498bf895b4)

**Comment by raphlinus** [comment]
Based on Daniel's investigation, this seems most likely to be a watertightness issue in the flatten stage, possibly related to fastmath (another issue that implicates fastmath is #581, so we should probably look at these together).

A good next step would be to examine the output of the flatten stage (ie the line soup buffer). We made some effort to make joins watertight, but it's very easy to image we missed something.
