### ISSUE TITLE
How: `scene.append_with_opacity(scene)`

### ISSUE THREAD

**Issue by simbleau** [linebender/vello#623]
I have a scenario in bevy_vello I want to provide users the ability to fade the entire scene's opacity.

Take for example, an SVG.

An SVG is a static scene, you could even say it I store it as an `Arc<Scene>`.

When someone wants to change the opacity of the entire image, how could I draw that opacity? Is there a blend mode that would do the trick?

**Comment by raphlinus** [comment]
What you want here is [push_layer](https://docs.rs/vello/latest/vello/struct.Scene.html#method.push_layer), and in particular where you get to specify the alpha. You *do* need to supply a clip shape, which in many cases can be the axis aligned bounding box enclosing the content.

A couple of notes. If you nest these deeply (more than 4) you might run into problems with the current implementation, as we don't fully implement the overflow of the blend stack. That's a bug though and if it becomes important we can prioritize it.

Also, I've explored making the clip shape optional. The [stack monoid paper](https://arxiv.org/abs/2205.11659) explains how to compute blend bounding boxes and there is prototype code there. However, wiring it all up is nontrivial. It's probably easiest to have the application provide the clip shape for now.

**Comment by DJMcNab** [comment]
I think we should close this issue, with this answer. We could open a new issue for making the clip shape optional, if needed.

**Comment by simbleau** [comment]
I implemented this for SVG/Lottie using a fullsize rect as mentioned.

The problem is that raw scenes dont have a size, and therefore no clip shape that makes sense.
But I'd maybe argue if a user is rendering a raw scene with bevy_vello, they can apply opacity how they want themselves.
