### ISSUE TITLE
IOS app crash 0.2.1

### ISSUE THREAD

**Issue by AngeloMateus** [linebender/vello#637]
IOS app crashes on launch with the following error:

```
-[MTLDebugComputeCommandEncoder dispatchThreadgroups:threadsPerThreadgroup:]:1054: failed assertion `(threadgroupsPerGrid.width(0) * threadgroupsPerGrid.y(1) * threadgroupsPerGrid.depth(1))(0) must not be 0.'
```

Previously tested working version: vello 0.1.0 (with bevy_vello 0.3.3)

Initially discussed [_here_](https://github.com/linebender/bevy_vello/issues/67)

Does anyone know how I can fix this?

**Comment by DJMcNab** [comment]
Thanks for the report.

There are a few things going on here:
1) We support iOS only on a best-effort basis.
2) That error suggests that one of the CPU side workgroup sizes is zero. These are set in https://github.com/linebender/vello/blob/984121d5eb004022893fae58fd0eb5059c769c04/vello_encoding/src/config.rs#L250-L269. Can you please confirm which of those values has a first component of `0` for you?
3) The WebGPU spec requires that this case [be supported](https://www.w3.org/TR/webgpu/#dom-gpucomputepassencoder-dispatchworkgroups). It is a bug in [wgpu](https://github.com/gfx-rs/wgpu) that this doesn't work. Can you please submit a minimal reproduction to them?
4) We should be able to work around this ourselves, as dispatching a command doesn't have any observable side effects.
5) We might run into the same issue with indirect buffers. That will likely require a more involved workaround, or changing the WebGPU spec to not support this case.
