### ISSUE TITLE
Drop shadows

### ISSUE THREAD

**Issue by StarArawn** [linebender/vello#640]
Support for drop shadows would be excellent! I did this in my own custom UI renderer by using SDF's for quads, but I imagine for any shape it might be a little bit more tricky.. 

You can see my quad sdf box shadow code here if it helps at all:
https://github.com/StarArawn/kayak_ui/blob/main/src/render/unified/shaders/sample_quad.wgsl#L86

**Comment by raphlinus** [comment]
For arbitrary shapes (and blurs of layers other than images) the best bet is to do image filters, which are on the longer term roadmap but require quite a bit of architectural and infrastructure work.

Doing blurred rounded rectangles shouldn't be too hard. The code linked above is simple and efficient, but not especially accurate (you'll have curvature discontinuities) if you look at isolines. A better approach is the [blurred rounded rectangle](https://raphlinus.github.io/graphics/2020/04/21/blurred-rounded-rects.html) technique from my blog a few years back.

Tactically, I think the best way to implement this is as another type of gradient. The PR to add conical gradients (#435) is probably a good guideline for what's involved. In brief, getting the gradient parameters encoded, doing processing (roughly analogous to a vertex shader) in draw_leaf, and of course computing the alpha values (analogous to a fragment shader) in fine.

This is a great issue for someone to get up to speed on the Vello codebase, help would be appreciated.

**Comment by msiglreith** [comment]
I would take a stab at implementing as it seems pretty straightforward and I'm also in need for it 👀
