### ISSUE TITLE
Infinitesimal stroked bezier fills whole tile

### ISSUE THREAD

**Issue by dominikh** [linebender/vello#650]
The scene
```
let mut scene = Scene::new();
let mut p: BezPath = BezPath::default();
p.move_to((399.997, 400.0002));
p.quad_to((399.998, 400.0002), (400., 400.));
scene.stroke(
    &Stroke::default(),
    Affine::IDENTITY,
    Color::rgb(1., 0., 0.),
    None,
    &p,
);
```

renders as a solid square
![image](https://github.com/user-attachments/assets/6bc1f127-6444-45c8-9f19-92a85c1ed5f9)

This seems very sensitive to the coordinates, and many translations of the coordinates don't reproduce the issue. The same issue reproduces with a cubic bezier, with the point `(400., 400.)` repeated.

**Comment by raphlinus** [comment]
It's very likely this is another manifestation of #644, which I believe is a watertightness issue in the expanded stroke outlines. It's in my queue to look at.

**Comment by raphlinus** [comment]
I'm not able to repro directly (or #616 either) from the given example, but I do see an artifact with the following:

```rust
        let mut p: BezPath = BezPath::default();
        p.move_to((399.997, 400.0002));
        p.quad_to((399.998, 400.0002), (400., 400.));
        p.line_to((390., 390.));
        let a = Affine::translate((31.90625, 23.98875));
        scene.stroke(
            &Stroke::new(2.0).with_caps(Cap::Butt),
            a,
            Color::WHITE,
            None,
            &p,
        );
```

It definitely appears to be a watertightness bug, and I suspect it's the same underlying issue. I should be able to track it down now that I've got a repro.

Curious why the variation in reproducibility, but we'll most likely get to that when we have a proposed fix.

**Comment by DJMcNab** [comment]
I suspect the difference could be a fast-math issue.

That's my general heuristic to explain if something is different on Mac :P

**Comment by raphlinus** [comment]
I have a tentative analysis and proposed fix for this particular case. Basically the tangent computed for the start cap is not bit-identical to the tangent for the parallel curves (even though mathematically it's the same). Change line 847 of flatten.rs from:

```rust
                    let tangent = cubic_start_tangent(pts.p0, pts.p1, pts.p2, pts.p3);
```

to

```rust
                    let tangent = pts.p3 - pts.p0;
```

I'm not sure this fixes everything (still investigating), but did want to send an update.

**Comment by raphlinus** [comment]
Quick followup on this, as I'm looking at PR'ing the change. It's to flatten.wsgl, not .rs, but of course a proper PR should also fix the CPU shader. Taking a look at this now, I think there are two cases: open subpaths (which the above patch addresses) and closed ones (which the above patch does not). I'll see if I can get a PR out soon.
