### ISSUE TITLE
Examples don't run on Raspberry Pi 4

### ISSUE THREAD

**Issue by sfjohnson** [linebender/vello#653]
So far I have `vkcube` and the wgpu examples working, but the wgpu examples always seem to use OpenGL, even if I set `WGPU_BACKEND=vulkan`. The simple Vello example gives `Error creating surface: NoCompatibleDevice`. I believe that error is [here](https://github.com/linebender/vello/blob/1f71fc945eda9336644d12894f8cd7da6a08625f/vello/src/util.rs#L53). Same result with both Wayland and X11.

Note that I'm on Raspberry Pi CM4 with only 1GB of RAM so the Rust code was compiled in a Docker container. Not sure if that would make a difference.

My understanding is that the RPi 4 hardware is not capable of full wgpu support, but seeing that the wgpu demos run, and Vulkan seems to be working, I thought it would be worth trying Vello as I'm very interested in this library. Please let me know if I can collect more logs to help investigate.

Thank you!

**Comment by DJMcNab** [comment]
I think this might be a duplicate of #326. We don't currently actively develop targeting OpenGL, but it would be interesting to have working. Can you try the change suggested in there of changing `::Primary` wgpu backends to include `OpenGL`?

I'm surprised that vkcube works for you, if you can't get wgpu to use Vulkan. Can you run `vulkaninfo` on your machine? What GPUs does it list there (under Device properties and extensions). In particular, what API version, etc. is present?

**Comment by sfjohnson** [comment]
Changing to `wgpu::Backends::GL` gives a different error:

```
thread 'main' panicked at examples/simple/src/main.rs:67:58:
Error creating surface: WgpuCreateSurfaceError(CreateSurfaceError { inner: Hal(FailedToCreateSurfaceForAnyBackend({})) })
```

This is `vulkaninfo --summary`. Let me know if you need the full log:

```
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 0.  Skipping ICD.
'DISPLAY' environment variable not set... skipping surface info
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.239


Instance Extensions: count = 22
-------------------------------
VK_EXT_acquire_drm_display             : extension revision 1
VK_EXT_acquire_xlib_display            : extension revision 1
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_EXT_surface_maintenance1            : extension revision 1
VK_EXT_swapchain_colorspace            : extension revision 4
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_portability_enumeration         : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_wayland_surface                 : extension revision 6
VK_KHR_xcb_surface                     : extension revision 6
VK_KHR_xlib_surface                    : extension revision 6

Instance Layers: count = 3
--------------------------
VK_LAYER_KHRONOS_validation Khronos Validation Layer     1.3.239  version 1
VK_LAYER_MESA_device_select Linux device selection layer 1.3.211  version 1
VK_LAYER_MESA_overlay       Mesa Overlay layer           1.3.211  version 1

Devices:
========
GPU0:
	apiVersion         = 1.2.255
	driverVersion      = 23.2.1
	vendorID           = 0x14e4
	deviceID           = 0xbe485fd3
	deviceType         = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
	deviceName         = V3D 4.2.14
	driverID           = DRIVER_ID_MESA_V3DV
	driverName         = V3DV Mesa
	driverInfo         = Mesa 23.2.1-1~bpo12+rpt3
	conformanceVersion = 1.3.6.1
	deviceUUID         = 2ed13185-e77c-e2ea-cfd5-078818d4e3e5
	driverUUID         = 1698c6ef-161f-3213-5159-557202953ee9
GPU1:
	apiVersion         = 1.3.255
	driverVersion      = 0.0.1
	vendorID           = 0x10005
	deviceID           = 0x0000
	deviceType         = PHYSICAL_DEVICE_TYPE_CPU
	deviceName         = llvmpipe (LLVM 15.0.6, 128 bits)
	driverID           = DRIVER_ID_MESA_LLVMPIPE
	driverName         = llvmpipe
	driverInfo         = Mesa 23.2.1-1~bpo12+rpt3 (LLVM 15.0.6)
	conformanceVersion = 1.3.1.1
	deviceUUID         = 6d657361-3233-2e32-2e31-2d317e627000
	driverUUID         = 6c6c766d-7069-7065-5555-494400000000
```

Note that `DISPLAY` isn't set as I'm not running things inside of a graphical environment. I'm testing with X11 by doing `startx ./simple`, and with Wayland using cage on top of wlroots. I did try to set some env vars to get rid of the ICD warning, but no luck. Not sure if that is part of the issue.

I did say that wgpu examples are using OpenGL but running the hello example gives back Vulkan, so to be honest I'm not sure:

```
[2024-08-02T11:06:57Z INFO  wgpu_examples::hello] Available adapters:
[2024-08-02T11:06:57Z INFO  wgpu_examples::hello]     AdapterInfo { name: "V3D 4.2.14", vendor: 5348, device: 3192414163, device_type: IntegratedGpu, driver: "V3DV Mesa", driver_info: "Mesa 23.2.1-1~bpo12+rpt3", backend: Vulkan }
[2024-08-02T11:06:57Z INFO  wgpu_examples::hello]     AdapterInfo { name: "llvmpipe (LLVM 15.0.6, 128 bits)", vendor: 65541, device: 0, device_type: Cpu, driver: "llvmpipe", driver_info: "Mesa 23.2.1-1~bpo12+rpt3 (LLVM 15.0.6)", backend: Vulkan }
[2024-08-02T11:06:57Z INFO  wgpu_examples::hello] Selected adapter: AdapterInfo { name: "V3D 4.2.14", vendor: 5348, device: 3192414163, device_type: IntegratedGpu, driver: "V3DV Mesa", driver_info: "Mesa 23.2.1-1~bpo12+rpt3", backend: Vulkan }
```

I guess my goal is to see if I can run Vello with Vulkan in the supported way, and to figure out if the (quite new) Raspberry Pi Vulkan driver is sufficient to run it.

**Comment by DJMcNab** [comment]
Unfortunately I don't have much more guidance available. As far as I know, we test using llvmpipe on CI, which isn't an ARM backend, but otherwise should be similar.

Does the `headless` example work for you?

**Comment by sfjohnson** [comment]
For the `headless` example it's erroring out [here](https://github.com/linebender/vello/blob/74b61558ad55449589d4a792cf7143b2b71e4bfd/examples/headless/src/main.rs#L82).

Sounds like this should be possible so I'll keep hacking away at it. Do you target a particular Vulkan API version or is that the job of wgpu?

**Comment by waywardmonkeys** [comment]
This is almost certainly a wgpu level thing.

**Comment by sfjohnson** [comment]
So the errors were due to the RPi's Vulkan driver not meeting wgpu's default limits. It looks like the Vulkan `downlevel_defaults` are not sufficient to run the Vello examples. I now have `headless` running by adding some custom limits [here](https://github.com/linebender/vello/blob/74b61558ad55449589d4a792cf7143b2b71e4bfd/vello/src/util.rs#L123), but the PNG is blank, likely caused by this error:

```
 ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkPipelineLayoutCreateInfo-descriptorType-03023 (0xf26ac9dd)]
    	Validation Error: [ VUID-VkPipelineLayoutCreateInfo-descriptorType-03023 ] Object 0: handle = 0x559100d2f0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf26ac9dd | vkCreatePipelineLayout(): max per-stage uniform buffer bindings count (1) exceeds device maxPerStageDescriptorUpdateAfterBindUniformBuffers limit (0). The Vulkan spec states: The total number of descriptors with a descriptorType of VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER and VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC accessible to any given shader stage across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceDescriptorIndexingProperties::maxPerStageDescriptorUpdateAfterBindUniformBuffers (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPipelineLayoutCreateInfo-descriptorType-03023)
```

So wgpu is trying to use a feature the Vulkan driver does not have. I'll make an issue on the wgpu repo. It likely won't be possible to have a full WebGPU implementation on RPi with Vulkan but I'll keep working on it to see if I can get Vello working.

Thanks!

**Comment by waywardmonkeys** [comment]
It may be that there's some ground in between the wgpu defaults and the "downlevel" limits where things can still work.

**Comment by sfjohnson** [comment]
I think wgpu is OK now, there was a Mesa update 2 months ago that fixes the above error. wgpu examples are now running in Vulkan without errors. With the Vello `headless` example it is working correctly with `--use-cpu`, but is outputting a blank PNG like before when run without that option. In the log everything seems to be working normally.

All the limits are now at `defaults` except for `max_texture_dimension_1d` and `max_texture_dimension_2d` which have been changed from `8192` to `4096`. I also tried `simple` but I get a blank screen with no errors. That could have something to do with having no graphical environment, so first I'm trying to get headless working. Any ideas?

**Comment by raphlinus** [comment]
If `--use-cpu` is working, then you can isolate which compute stage is failing by setting `force_gpu_from` to various stages. The easiest way to do that is to edit vello/src/shaders.rs.

**Comment by sfjohnson** [comment]
`clip_reduce` and later are working on GPU, but force GPU from `draw_leaf` causes a blank PNG. So it looks like the issue is in `draw_leaf`. Any way I can get you some more logs? I've got `RUST_LOG=debug` on which is very chatty, but I don't see anything going wrong.

**Comment by raphlinus** [comment]
That's encouraging, as it means most of the stages (including some complicated ones) are working. Unfortunately, figuring out exactly what's going wrong requires superhuman debugging abilities. We have as part of our roadmap comparing the output of GPU shaders with the CPU ones (and draw_leaf turns out to be one of the simpler ones, as it's deterministic), but at the moment that has to be done by hand.

**Comment by sfjohnson** [comment]
I have `simple` working, just needed to wait a few seconds for it to initialise. I'm going to start using the library now with that `force_gpu_from` hack in place. At the moment I don't know much Rust or any WGSL but hopefully I can look into the shader issue as I learn. Thanks for your help.
