### ISSUE TITLE
High GPU usage and Slow Framerate on Integrated Graphics.

### ISSUE THREAD

**Issue by TheNachoBIT** [linebender/vello#658]
Hello Vello Developement Team! I hope y'all are having a good day/night!

I'm currently having an issue in one of the examples inside of a library i'm making called [Bella](https://github.com/bella-project/bella), which is powered by Vello.

This example is [stress_test_1000_shapes.rs](https://github.com/bella-project/bella/blob/main/examples/stress_test_1000_shapes.rs), where there's a parent (the yellow shape) that contains 1000 white circles, all on top of each other.

![image](https://github.com/user-attachments/assets/591fc262-c5b9-45ac-bce8-6b03a81ddd43)

## The Problem.

Running this on an `Intel(R) UHD Graphics 630` (2GB of VRAM), the usage hits 95%-100% and the framerate is extremely slow.

![image](https://github.com/user-attachments/assets/9e625101-319d-41d8-8cdd-676998e6a152)

## Things i've already checked.

- This is not a CPU issue, the usage of it is extremely low.
- This is not a VRAM issue, i still had 1.2 GB of space left.
- This is not a Driver issue, i have them all up-to-date.

If there's any info y'all need about this, i'll be happy to send it.

Thank you, and again, have a good day/night y'all :D

**Comment by DJMcNab** [comment]
We don't handle cases where there are large numbers of items in the same tile very gracefully. If the circles aren't all on top of each other, are the performance characteristics better?

Can you reproduce this same issue by zooming out significantly in our `with_winit` example? 

There are some plans to make this better, see e.g. [#gpu > Sparse Strip Path Rendering](https://xi.zulipchat.com/#narrow/stream/197075-gpu/topic/Sparse.20strip.20path.20rendering)

**Comment by TheNachoBIT** [comment]
@DJMcNab Thank you for responding!

When you spread out the circles, yes, the problem goes away. GPU usage goes down and framerate goes back to normal!

![image](https://github.com/user-attachments/assets/f7d72c02-a4b0-490a-9d86-4f51e2e0751a)
![image](https://github.com/user-attachments/assets/6182f837-3382-4dd6-9b7a-ecd04e74d2e3)

I'm now going to test the `with_winit` example to see if there's any issues.

And i'm glad that there are plans to make this better! :D

**Comment by DJMcNab** [comment]
I'm not sure whether this is a useful issue to keep open. My suggestion for you would be to just avoid creating such degenerate scenes - if you/your users control the content, that should be viable for now.

**Comment by TheNachoBIT** [comment]
@DJMcNab I personally think you should keep this issue opened, atleast until there's a solution about it. Because having this amount of objects/shapes overlapping eachother will happen if you have games that depend a lot of shapes and detail.

So for example, if i want to make a bullet hell game that is fully vectorized, sadly i wouldn't be able to choose this renderer, because i could stumble upon this issue.

This is one of many examples, and this issue happening mid-game developement could've be kind of a bummer.

**Comment by DJMcNab** [comment]
I don't think this issue occurs when there are a handful (say ~200) items in the same tile - it only becomes significant with huge numbers of items.

I would be extremely surprised if a bullet hell game had a meaningful reason to run into this issue. This is absolutely something we are aware of, but it only manifests in unrealistic cases.

**Comment by dominikh** [comment]
This seems like a variant of #419 and #305 and #409.

**Comment by dominikh** [comment]
> I don't think this issue occurs when there are a handful (say ~200) items in the same tile - it only becomes significant with huge numbers of items.

OP ran into this with 1001 items; is that so much bigger than 200?

**Comment by DJMcNab** [comment]
I don't have a good sense of what the problematic numbers are. I did misread the initial message as containing 10_000 items.
I have observed that I don't really run into this issue in our mmark example, and that does have some quite significant overlap.

Nevertheless, I think this issue has the same cause as those other issues, and so can be closed. Thanks for pointing that out. I'll leave closing this to the author to do so, if they're satisfied.

**Comment by TheNachoBIT** [comment]
@DJMcNab If you want to see an example of what people can do in a 2D engine, you can take a look at custom Geometry Dash levels.

There are some that are **really object dense**, and yet the game is so optimized that it can render them in a potato:

[Sedulous by Samifying (205.156 objects)](https://www.youtube.com/watch?v=mNaXAjk_t4Y)
[Ultra Violence by Xender Game (172.482 objects)](https://www.youtube.com/watch?v=tL2X3Fy0BUQ)
[Change of Scene by Bli (69.211 objects)](https://www.youtube.com/watch?v=alafxkFTprU)

This game runs on textures and not on vectors, but still, its quite an achievement from the developer that you can run these.

Just a quick question before closing it, is the Sparse Strip Path Rendering one of the goals for Vello 0.3?

**Comment by TheNachoBIT** [comment]
Also @dominikh thank you for pointing out that i'm spawning an extra shape lmao, i'll fix that tomorrow!

**Comment by DJMcNab** [comment]
> Just a quick question before closing it, is the Sparse Strip Path Rendering one of the goals for Vello 0.3?

I don't know. I suspect we might release a v0.3 before that work is complete.

**Comment by TheNachoBIT** [comment]
@DJMcNab 

> I don't know. I suspect we might release a v0.3 before that work is complete.

Nice! Can't wait to see that in action! I've seen the XulipChat about that, and y'all are implementing insane stuff! Good luck to y'all and i hope the rendering technique goes well :D

> And I think my point about having that many objects in the same location still stands. Those do have that many objects, but the total number on-screen and in one location is still relatively small.

Y'know, you're probably right! I think one way to find out is to make a scene *that* dynamic. Still i'm very glad that despite all of it, y'all are implementing techniques that counter these issues anyways. That shows a lot of love and dedication to this project and i can't wait to see how Vello evolves.

I'll close this for now, and i'll wait to see how progress on this goes.

As always, thank you so much for responding, i appreciate it a lot!
Have a fantastic day/night :D
