### ISSUE TITLE
Stack of scaled layers breaks at certain window size

### ISSUE THREAD

**Issue by dominikh** [linebender/vello#668]
When rendering with a base color other than black, the following scene

```
scene.push_layer(BlendMode::new(Mix::Normal, Compose::SrcOver), 1.0, Affine::scale(2.0), &Rect::new(0.0, 0.0, 1024.0, 1024.0)); 
scene.push_layer(BlendMode::new(Mix::Normal, Compose::SrcOver), 1.0, Affine::scale(2.0), &Rect::new(0.0, 0.0, 1024.0, 1024.0)); 
scene.push_layer(BlendMode::new(Mix::Normal, Compose::SrcOver), 1.0, Affine::scale(2.0), &Rect::new(0.0, 0.0, 1024.0, 1024.0)); 
scene.push_layer(BlendMode::new(Mix::Normal, Compose::SrcOver), 1.0, Affine::scale(2.0), &Rect::new(0.0, 0.0, 1024.0, 1024.0)); 
scene.push_layer(BlendMode::new(Mix::Normal, Compose::SrcOver), 1.0, Affine::scale(2.0), &Rect::new(0.0, 0.0, 1024.0, 1024.0)); 

scene.pop_layer();
scene.pop_layer();
scene.pop_layer();
scene.pop_layer();
scene.pop_layer();
```

will display the base color for small window sizes, but black for large window sizes. In my case, "small" is any window with a pixel area less than 2**20.

To reproduce the problem, I've needed at least 5 layers, and a scale transform that's >1.0; but even 1.00001 was sufficient.

**Comment by DJMcNab** [comment]
I strongly suspect that this is a duplicate of #366. The reason it displays black is because the rendering never occurs, because you run out of memory in the blend stack.

However, I don't know why a different scale transform would have any impact here, so I'm leaving this open.

**Comment by dominikh** [comment]
Indeed, changing https://github.com/linebender/vello/blob/a00cd9ffb617810980487b88a6bfa13d3a642e40/vello_encoding/src/config.rs#L403-L404 to 1<<21 "fixes" it for this particular scene.

**Comment by dominikh** [comment]
I'll chalk this up to getting unlucky with what tiles were occupied at different scales and close it as a duplicate of #366.
