### ISSUE TITLE
Feature request: more control about the pixel alignment (?) of `draw_image()`

### ISSUE THREAD

**Issue by yutannihilation** [linebender/vello#719]
(I'm not very familiar with graphics things, so excuse me if I'm missing some point)

Currently, drawing these 4 pixels by `draw_image()` gives the following result.
I'm not familiar with graphics things, so I'm not sure what's the correct behavior, but, in my usage, I prefer

1. sharp edge
2. the color is drawn at the center of each pixel instead of the top left corner

(cf. https://github.com/yutannihilation/vellogd-r/pull/14#issuecomment-2423652705 is the expected result)

Regarding the first request, I think this is what I should handle by adding extra pixels at the left edge and at the bottom edge and then cut.

For the second one, does it make sense to introduce some option to `Scene::draw_image()`? Probably, adding `kurbo::Affine::translate((0.5, 0.5))` to `brush_transform` of `Scene::fill()`.

```rust
    let mut blob: Vec<u8> = Vec::new();
    [Color::RED, Color::BLUE, Color::BLUE, Color::BLUE]
        .iter()
        .for_each(|c| {
            let b = c.to_premul_u32().to_ne_bytes();
            blob.push(b[3]);
            blob.push(b[2]);
            blob.push(b[1]);
            blob.push(b[0]);
        });

    let data = vello::peniko::Blob::new(Arc::new(blob));
    let image = vello::peniko::Image::new(data, vello::peniko::Format::Rgba8, 2, 2);
    scene.draw_image(
        &image,
        Affine::scale(300.0).then_translate((100.0, 100.0).into()),
    );
```

![image](https://github.com/user-attachments/assets/c89d1c8e-a823-4abe-895e-f66e8e2c5635)

**Comment by yutannihilation** [comment]
Thanks for investigating!

> I'm not sure what the expected behaviour for pixel position is.

I too am not sure. I guess this matters less when the number of pixels is large, so this might not be very important.

**Comment by dfrg** [comment]
Needed a bit of a break from other things so I took a swing at this. Please test out #722 and see if this provides the expected rendering.

**Comment by yutannihilation** [comment]
Wow, thanks for the fix! I confirmed it gives the expected result perfectly (https://github.com/yutannihilation/vellogd-r/pull/18).
