### ISSUE TITLE
Question: Can I avoid constant reallocations when using multiple surfaces with a single Renderer?

### ISSUE THREAD

**Issue by rrconkle** [linebender/vello#729]
Hello

I have a surface for every monitor. Due to this, nearly every call to `Renderer::render_to_surface` reallocates when there is more than one monitor connected ([lib.rs#L465](https://github.com/linebender/vello/blob/main/vello/src/lib.rs#L465)).

Is there a way to avoid this? Sould I use multiple `Renderer`s?

**Comment by DJMcNab** [comment]
For this use-case, I would ignore the built-in support for rendering to a `Surface`, and instead manage the blitting manually yourself. See the caveat on [Renderer](https://docs.rs/vello/latest/vello/struct.Renderer.html), that we know that this limitation isn't ideal.

Essentially, my planned future design is to have a single core "renderer", and then you would have multiple `RenderContext`s (name TBD) for each thread of rendering. But finding the bandwidth to implement that is a challenge.

**Comment by rrconkle** [comment]
How exactly would I do that? `render_to_surface` seems to use multiple private types (mainly `WgpuEngine`).

**Comment by DJMcNab** [comment]
You'd use `render_to_texture`, and create your own blit pipeline (probably modelled on the built-in blit pipeline) using the wgpu primitives.

As I say, this is known to be non-ideal.
