### ISSUE TITLE
Fate / status of `r8` ifdef in shaders

### ISSUE THREAD

**Issue by waywardmonkeys** [linebender/vello#755]
In `fine.wgsl`:

```
#ifdef r8
// The R8 variant is only available via an internal extension in Dawn native
// (see https://dawn.googlesource.com/dawn/+/refs/heads/main/docs/tint/extensions/chromium_internal_graphite.md).
#enable chromium_internal_graphite;
#endif
```

```
@group(0) @binding(5)
#ifdef r8
var output: texture_storage_2d<r8unorm, write>;
#else
var output: texture_storage_2d<rgba8unorm, write>;
#endif
```

Is this used by anything still?

It seems like `r8unorm` is a valid part of the WebGPU specification now, so maybe this is a hold over from earlier days.

Is this something that can be used from the renderer code or was that part of something else as well?

**Comment by raphlinus** [comment]
There are two paths going forward for glyph caching. One is to render r8 textures into an atlas, as was the original plan. In that case, a reduced pipeline would be useful, as it's possible to strip out stuff that's not relevant for (non-emoji) glyph rendering, like clipping, gradients, etc.

The other of course is sparse strips. In that case, there's no need for an r8 texture, as the representation of rendered glyphs (and retained path renders) is not a texture, but two buffers containing the sparse strip representation.

In both cases, I think it makes sense to strip out the r8 and `#ifdef full` stuff now, to keep things clean. If somebody (not me!) has the motivation to add classic atlas-based glyph caching to Vello, they can re-add the r8 stuff, and the hassle to do that is minimal compared with the overall work.

So imho that weighs in favor of landing #754.

**Comment by waywardmonkeys** [comment]
Should I also remove `r8` in #754 then or a separate PR?

This will remove 3 permutations of the `fine` shader, so that might be a small start up time improvement as well!

**Comment by raphlinus** [comment]
I might do that as a separate PR. It's *possible* someone is still using that and wants it, but I'm almost sure the non-`full` configuration is just broken and unmaintained.

**Comment by waywardmonkeys** [comment]
Okay, 2 PRs are in ... someone approves them and I'll land them over the weekend or whenever.
