### ISSUE TITLE
Regression: Repeating chunks of 3 to 5 missed frames about twice a second in with_winit following #752

### ISSUE THREAD

**Issue by xorgy** [linebender/vello#767]
Something in #752 (bisected) is causing the with_winit example to miss groups of 3 to 5 frames at a regular interval now.

I am running it on Mesa 24.3 RADV, on a Radeon VII. This seems to be a present issue maybe so I suspect others may also be affected. The issue is present on both X11 and Wayland, though on Wayland it has some additional effect on present.

**Comment by DJMcNab** [comment]
This is due to the `notify-debouncer-mini` update - we seem to be getting spurious rebuilds of the render context. Looking into it now.

**Comment by DJMcNab** [comment]
What seems to be happening is that when we read the shaders, that counts as a read of the file, and so triggers notify. What I don't understand is:
1) Why this didn't happen before
2) How `notify-debouncer-mini` can ever be useful. Surely you want to action the report, but if it reports the things you did in response that's useless? There's no way to reliably detect that case without a risk of false positives.
