### ISSUE TITLE
Cross-platform runtime

### ISSUE THREAD

**Issue by raphlinus** [linebender/vello#95]
This is a tracking issue for work in progress. The goal is to get piet-gpu running on DX12 and Metal as well as Vulkan, as well as to make it a suitable target for the upcoming "compute shader 101" class (an alternative to wgpu, which will probably also be supported - having both in good shape would be a nice problem to have). I also want to improve some of the basic infrastructure, which is quite hacky in places.

Work is required across the entire piet-gpu-hal subcrate, with minor changes expected in the clients. The current architecture of piet-gpu-hal roughly follows gfx-hal and wgpu, but I will adapt it a bit.

There are PR's in progress for both DX12 (#80) and Metal (#93). However, I'm shortly going to need to make changes that are much less localized to a particular backend. I'll probably land #94 then do the bulk of the work in #80 - the goal is to reduce friction, rather than have things in clean commits.

There are some design decisions coming up. One is how extensive the polyfill should be in the lower (piet_gpu::Device) layer. If you look at [buffer<->image copies in gfx-hal's dx12 backend](https://github.com/gfx-rs/gfx/blob/14e87eff2ec6470c998c5ef991b8813c545687dd/src/backend/dx12/src/command.rs#L2402), they do a fairly elaborate dance to split the copy into individual rows when the stride doesn't agree with DX12's 256 byte alignment. I'm much more inclined to run a compute shader instead. I'm *also* inclined to just make the lower level operation fail and have the hub (roughly equivalent to wgpu) schedule the work.

Another major area of work involves staging buffers, especially creation of buffers with initial contents. WebGPU has a clever approach to that problem: you can create a buffer as mapped on creation, even if it's not host-visible. When running on discrete GPU, what happens under the hood is the creation of a staging buffer and a copy to the real buffer at some point after buffer creation but before first use. I'm inclined to do something similar, but it will bring in a fair amount more resource tracking at the hub layer. On Metal, this should probably map to [newBufferWithBytes:](https://developer.apple.com/documentation/metal/mtldevice/1433429-newbufferwithbytes) though there is a debate whether it's better to let Metal handle this or do our own layer and treat Metal as just a nonstandard syntax for Vulkan.

(there's more possible complexity, including a `Vec<u8>` like interface to the uninitialized buffer slice, as well as choosing whether to use a staging buffer on readback, but I think I will defer that)

I will also need to beef up the shader compilation story, as it will bring in spirv-cross, and dxc if I want to use SM6. I plan to keep using ninja for now, though the build files will become considerably more tedious. A better tool (possibly using [hassle-rs](https://crates.io/crates/hassle-rs), and almost definitely using [naga](https://github.com/gfx-rs/naga) when it's more mature) is possible, but I think I'll accept a bit of tedium for now.

One thing I *could* do as part of this cycle is real memory allocation - currently I do an API alloc for each resource, the equivalent of CreateCommittedResource. But that's a performance concern only and shouldn't affect the external interface, so I'm inclined to defer it. I'm looking at both [gpu-alloc](https://crates.io/crates/gpu-alloc) and [gpu-allocator](https://crates.io/crates/gpu-allocator) and haven't decided yet.

**Comment by raphlinus** [comment]
A little followup. I was actually wrong about CmdBuf not having a device reference, but I don't think that changes the calculus too much.

Another goal which should be in scope for this is providing some validation at the hub level, as I expect that to be a serious quality of life issue for developers (including myself).

**Comment by DJMcNab** [comment]
We now use [wgpu](https://wgpu.rs) as our runtime!
